name: Java CI/CD

on:
  push:
    branches: 'main2'
  pull_request:
    branches: 'main2'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Configurar Java 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Cache do repositório Maven
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Compilar com Maven
      run: mvn -B compile

    - name: Executar testes
      run: mvn -B test

    - name: Empacotar (build do JAR)
      run: mvn -B package
